version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
    ports:
      - "3307:3306"  # Utiliser le port 3307 sur l'hôte au lieu de 3306

  app:
    build: .  # Assurez-vous qu'il y a un Dockerfile dans le contexte de construction
    image: emna_belkhiria_5nids1_g1_tpfoyer  # Nom de l'image modifié pour respecter les règles
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SERVER_PORT: 8089
      SERVER_SERVLET_CONTEXT_PATH: /tpfoyer
    depends_on:
      - db  # Assurez-vous que l'app démarre après la base de données
