version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql  # Ajouter un volume pour persister les données de la base de données

  app:
    image: emnabelkhiria-5nids1:latest  # Utiliser l'image construite
    ports:
      - "8089:8089"  # Map du port 8089 de la machine hôte vers le port 8089 du conteneur
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SERVER_PORT: 8089
      SERVER_SERVLET_CONTEXT_PATH: /tpfoyer
    depends_on:
      - db  # Assurez-vous que la base de données est prête avant de démarrer l'application

volumes:
  db_data:  # Définir un volume pour persister les données de la base de données
