version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: tp-foyer-db  # Nom du conteneur pour la base de données
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql  # Volume pour persister les données de la base de données
    networks:
      - app-network

  app:
    image: emna0203/emnabelkhiria-5nids1:latest  # Image de l'application
    container_name: tp-foyer-app  # Nom du conteneur pour l'application
    ports:
      - "8089:8089"  # Mappage du port 8089 de l'hôte vers le conteneur
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SERVER_PORT: 8089
      SERVER_SERVLET_CONTEXT_PATH: /tpfoyer
    depends_on:
      - db  # Dépendance à la base de données
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:  # Volume persistant pour les données MySQL
