version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql  # Volume pour persister les données de la base de données

  app:
    image: emnabelkhiria-5nids1:latest  # Image de l'application
    ports:
      - "8089:8089"  # Mappage du port 8089 de l'hôte vers le conteneur
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SERVER_PORT: 8089
      SERVER_SERVLET_CONTEXT_PATH: /tpfoyer
    depends_on:
      - db  # Dépendance à la base de données

  zap:
    image: owasp/zap2docker-stable
    container_name: zap
    ports:
      - "8090:8090"  # Port d'accès à l'interface web de ZAP
    entrypoint: ["zap.sh", "-daemon", "-port", "8090", "-config", "api.disablekey=true"]
    volumes:
      - ./zap/wrk:/zap/wrk:rw  # Volume pour l'intégration des fichiers de travail avec ZAP
    depends_on:
      - app  # ZAP dépend de l'application pour le scan

volumes:
  db_data:  # Volume persistant pour les données MySQL
