version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: emnabelkhiria-5nids1:latest
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SERVER_PORT: 8089
      SERVER_SERVLET_CONTEXT_PATH: /tpfoyer
    depends_on:
      - db

  zap:
    image: zaproxy/zap-stable
    container_name: zap-${CI_COMMIT_REF_NAME}  # Utilisez un nom dynamique pour éviter les conflits
    ports:
      - "8090:8090"
    entrypoint: ["zap.sh", "-daemon", "-port", "8090", "-config", "api.disablekey=true"]
    volumes:
      - ./zap/wrk:/zap/wrk:rw
    depends_on:
      - app

volumes:
  db_data:
