version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
    ports:
      - "3307:3306"  # Le port hôte 3307 est mappé au port 3306 du conteneur
    volumes:
      - db_data:/var/lib/mysql  # Volume persistant pour les données MySQL
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=example"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  app:
    image: emnabelkhiria-5nids1:latest  # Utiliser l'image construite par Jenkins
    ports:
      - "8089:8089"  # Mapper le port 8089 de l'hôte au port 8089 du conteneur
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SERVER_PORT: 8089
      SERVER_SERVLET_CONTEXT_PATH: /tpfoyer
    depends_on:
      db:  # Assurer que le conteneur de la base de données est prêt avant l'application
        condition: service_healthy  # Utiliser une condition pour vérifier que la base de données est prête

volumes:
  db_data:  # Volume persistant pour les données MySQL
