version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
    ports:
      - "3307:3306"  # Port mappé pour MySQL
    volumes:
      - db_data:/var/lib/mysql  # Volume pour persister les données de la base de données
    networks:
      - app-network  # Réseau personnalisé pour la communication avec l'application

  tp-foyer-app:  # Nom du service ajusté pour correspondre à la commande 'docker inspect' dans la pipeline
    image: emnabelkhiria-5nids1:latest  # Image de l'application
    ports:
      - "8089:8089"  # Mappage du port 8089 de l'hôte vers le conteneur
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: example
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SERVER_PORT: 8089
      SERVER_SERVLET_CONTEXT_PATH: /tpfoyer
    depends_on:
      - db  # Dépendance à la base de données
    networks:
      - app-network  # Réseau personnalisé pour la communication avec la base de données

networks:
  app-network:  # Définition du réseau personnalisé pour les services

volumes:
  db_data:  # Volume persistant pour les données MySQL
